// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Document struct {
	Repo            string
	Rkey            string
	PublicationRepo string
	PublicationRkey string
	DocumentJson    []byte
}

type Publication struct {
	Repo       string
	Rkey       string
	RecordJson []byte
}
