#!/bin/sh

set -e

ROOT_DIR="$(CDPATH="" cd -- "$(dirname -- "$0")/.." && pwd -P)"

mkdir -p "$ROOT_DIR"/bin

go build -o "$ROOT_DIR"/bin/benchdiff "$ROOT_DIR"/cmd/benchdiff

exec "$ROOT_DIR"/bin/benchdiff "$@"
