#!/bin/sh

set -e

cd "$(git rev-parse --show-toplevel)"

script/bindown -q install gofumpt
script/bindown -q install handcrafted

git ls-files -o -c --exclude-standard -- *.go |
 bin/handcrafted |
 xargs bin/gofumpt -w
