#!/bin/bash

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

usage_pattern="<!--- start usage output --->*<!--- end usage output --->"

usag_sub="$(cat <<EOF
<!--- start usage output --->
\`\`\`
$(COLUMNS=100 script/benchdiff --help)
\`\`\`
<!--- end usage output --->
EOF
)"

readme="$(cat README.md)"
echo "${readme//$usage_pattern/$usag_sub}" > README.md

tmpl_pattern="<!--- start template --->*<!--- end template --->"

tmpl_sub="$(cat <<EOF
<!--- start template --->
\`\`\`
$(script/benchdiff --show-default-template)
\`\`\`
<!--- end template --->
EOF
)"

readme="$(cat README.md)"
echo "${readme//$tmpl_pattern/$tmpl_sub}" > README.md
