#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

[ -n "$GITHUB_TOKEN" ] || {
  echo GITHUB_TOKEN must be set
  exit 1
}

script/bindown -q install goreleaser
script/bindown -q install semver-next

GITHUB_SHA="${GITHUB_SHA:-"$(git rev-parse HEAD)"}"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-"WillAbides/benchdiff"}"

bin/semver-next "$GITHUB_REPOSITORY" -r "$GITHUB_SHA" --create-tag --require-labels

git fetch --tags

bin/goreleaser release
