name: releasable
on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - reopened
  workflow_dispatch:
jobs:
  releasable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: script/bindown -q install semver-next
      - name: check releasable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bin/semver-next "$GITHUB_REPOSITORY" -r "$GITHUB_SHA" --require-labels
